Repository softeerbootcamp4th/Team1-Strawberry-BE, pull requests merged in 2024-08, with the labels that each got.

#73 BaseResponse 적용 및 API 문서화 작업합니다.
  src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/advice/QuizControllerAdvice.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/controller/QuizController.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/exception/QuizNotFoundException.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
  src/main/java/com/hyundai/softeer/backend/domain/user/controller/AuthController.java
  src/main/java/com/hyundai/softeer/backend/global/dto/BaseResponse.java
  src/main/java/com/hyundai/softeer/backend/global/status/BaseResponseStatus.java
Labels: 🥨 feat, :waffle: docs

#81 랭킹 조회 API 추가합니다.
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/entity/EventUser.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/entity/DrawingLotteryEvent.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/repository/DrawingLotteryRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/dto/RankDto.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryService.java
  src/main/java/com/hyundai/softeer/backend/global/dto/BaseResponse.java
Labels: 🥨 feat

#87 Release/v1.0.2
  gradle.properties
Labels: :cake: relaese

#92 추첨 이벤트 추첨 구현
  src/main/java/com/hyundai/softeer/backend/domain/event/dto/ApiKeyRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/event/dto/EventRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/event/service/EventService.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/dto/RankDto.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/entity/LotteryEvent.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/exception/AlreadyDrawedException.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryService.java
  src/main/java/com/hyundai/softeer/backend/domain/prize/entity/Prize.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/SubEventRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/WinnerCandidate.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/WinnerInfo.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/repository/SubEventRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/user/entity/User.java
  src/main/java/com/hyundai/softeer/backend/domain/winner/entity/Winner.java
  src/main/java/com/hyundai/softeer/backend/domain/winner/repository/WinnerRepository.java
  src/main/java/com/hyundai/softeer/backend/global/config/SwaggerConfig.java
  src/main/java/com/hyundai/softeer/backend/global/exception/error/JsonParseException.java
  src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/hyundai/softeer/backend/global/utils/ParseUtil.java
  src/test/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationServiceTest.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryServiceTest.java
  src/test/java/com/hyundai/softeer/backend/global/utils/ParseUtilTest.java
Labels: 🥨 feat

#95 EventUser Info API 변경합니다.
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/EventUserController.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/exception/EventUserNotFoundException.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/service/EventUserService.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryServiceTest.java
Labels: :pancakes: fix, 🥨 feat

#99 EventUserRepository 단위 테스트
  build.gradle
  src/main/java/com/hyundai/softeer/backend/domain/event/entity/Event.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
  src/test/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepositoryTest.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
  src/test/resources/sql/integration-h2.sql
Labels: 🥨 feat, :tamale: test

#110 드로잉 추첨 이벤트 테이블 및 추첨 메서드 도메인 변경합니다.
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/entity/LotteryEvent.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/controller/SubEventController.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/entity/SubEvent.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/service/SubEventService.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
  src/test/java/com/hyundai/softeer/backend/domain/subevent/service/SubEventServiceTest.java
  src/test/resources/sql/integration-h2.sql
Labels: :sandwich: refactor

#107 단축 URL 생성 및 Redirect 구현합니다.
  build.gradle
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/EventUserController.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/SharedUrlController.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/EventUserInfoDto.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/EventUserInfoRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/RedirectUrlDto.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/SharedUrlDto.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/entity/EventUser.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/exception/NonPlayedUserException.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/exception/SharedUrlNotFoundException.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/service/EventUserService.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/enums/SubEventType.java
Labels: 🥨 feat

#189 대기열을 기능 추가합니다.
  src/main/java/com/hyundai/softeer/backend/BackendApplication.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/EnqueueDto.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingEnqueueBodyRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueStatusDto.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/exception/WaitingInvalidTokenException.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/controller/QuizFirstComeController.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeSubmitRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/QuizFirstComeService.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/scheduler/QueueScheduler.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/service/QueueService.java
  src/main/java/com/hyundai/softeer/backend/global/utils/DateUtil.java
Labels: 🥨 feat

#191 Release/v1.2.0
  gradle.properties
  src/main/java/com/hyundai/softeer/backend/BackendApplication.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/EnqueueDto.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingEnqueueBodyRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueStatusDto.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/exception/WaitingInvalidTokenException.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/controller/QuizFirstComeController.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeSubmitRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/QuizFirstComeService.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/scheduler/QueueScheduler.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/service/QueueService.java
  src/main/java/com/hyundai/softeer/backend/global/utils/DateUtil.java
Labels: :cake: relaese

#195 Hotfix/v1.2.0 release1
  build.gradle
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingEnqueueBodyRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/controller/QuizFirstComeController.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/CounterService.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/QuizFirstComeService.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/winnerdraw/QuizWinnerDrawRedis.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/winnerdraw/QuizWinnerDrawSync.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/service/QueueService.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/rank/DrawingRankRedis.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/rank/DrawingRankSync.java
Labels: :pancakes: fix, :cake: relaese

#202 드로잉 이벤트 마스킹, 랜덤 메세지, 로직 변경합니다.
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/scheduler/QueueScheduler.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/ScoreCalculator.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/rank/DrawingRankSync.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/dto/RankDto.java
  src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java
  src/main/resources/messages.properties
  src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
Labels: :pancakes: fix, 🥨 feat

#218 Feat/#153 admin page
  .gitignore
  admin-frontend/.prettierrc.js
  admin-frontend/package.json
  admin-frontend/src/_nav.js
  admin-frontend/src/components/AppBreadcrumb.js
  admin-frontend/src/routes.js
  admin-frontend/src/views/charts/Charts.js
  admin-frontend/src/views/dashboard/Dashboard.js
  admin-frontend/src/views/event/Event.js
  admin-frontend/src/views/event/detail/EventDetail.js
  admin-frontend/src/views/event/detail/EventParticipants.js
  admin-frontend/src/views/purchaser/purchaser.js
  admin-frontend/src/views/user/user.js
  src/main/java/com/hyundai/softeer/backend/domain/car/repository/CarRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/event/controller/EventController.java
  src/main/java/com/hyundai/softeer/backend/domain/event/dto/EventCreateRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/event/dto/EventUserCountDTO.java
  src/main/java/com/hyundai/softeer/backend/domain/event/dto/UpdateEventPeriodRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/event/entity/Event.java
  src/main/java/com/hyundai/softeer/backend/domain/event/repository/EventRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/event/service/EventService.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/EventUserController.java
  src/main/java/com/hyundai/softeer/backend/domain/eventuser/service/EventUserService.java
  src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/controller/QuizFirstComeController.java
  src/main/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryService.java
  src/main/java/com/hyundai/softeer/backend/domain/purchaser/controller/PurchaserController.java
  src/main/java/com/hyundai/softeer/backend/domain/purchaser/dto/EventPurchaserCount.java
  src/main/java/com/hyundai/softeer/backend/domain/purchaser/dto/PurchaserDto.java
  src/main/java/com/hyundai/softeer/backend/domain/purchaser/entity/Purchaser.java
  src/main/java/com/hyundai/softeer/backend/domain/purchaser/repository/PurchaserRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/purchaser/service/PurchaserService.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/controller/SubEventController.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/SubEventSimpleDto.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/UpdateSubEventPeriodRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/UpdateWinnerMetaRequest.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/entity/SubEvent.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/repository/SubEventRepository.java
  src/main/java/com/hyundai/softeer/backend/domain/subevent/service/SubEventService.java
  src/main/java/com/hyundai/softeer/backend/domain/user/controller/UserController.java
  src/main/java/com/hyundai/softeer/backend/domain/user/dto/UserDetailDto.java
  src/main/java/com/hyundai/softeer/backend/domain/user/service/UserService.java
  src/main/java/com/hyundai/softeer/backend/domain/winner/dto/WinnerInfoDto.java
  src/main/java/com/hyundai/softeer/backend/domain/winner/entity/Winner.java
  src/test/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepositoryTest.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
  src/test/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryServiceTest.java
  src/test/java/com/hyundai/softeer/backend/infra/s3/service/S3ServiceTest.java
Labels: 🥨 feat

#226 Hotfix/v1.2.3 release3
  src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/PreviewController.java
  src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java
Labels: :pancakes: fix, :cake: relaese
